### ISSUE TITLE
Error with Touch Configuration

### ISSUE THREAD

**Issue by max2play** [arbalet-project/arbasdk#3]
Hi,
when using the default touch-configuration this error occurs almost imediatly after starting an app:

```
Arbalet hardware initialization successful
Touch calibrated
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/arbalet_core-3.0.0-py2.7.egg/arbalet/core/link/abstract.py", line 66, in run
    data_follows = self.write_led_frame(self._arbalet.end_model)
  File "/usr/local/lib/python2.7/dist-packages/arbalet_core-3.0.0-py2.7.egg/arbalet/core/link/arduino.py", line 148, in write_led_frame
    raise ValueError("Expected one command of {}, got {}".format(commands, ready))
ValueError: Expected one command of ['B', 'D'], got 

```

This does not occur, when using the normal configuration. Any ideas?

**Comment by ymollard** [comment]
`expected <something>, got <nothing>` means that no data could be read from serial. I'd say that your Arduino is busy establishing the connection with the touch sensor which does not answer and thus can't reply to the SDK. Check that your sensor is well connected and actually works by using the [example provided by the Adafruit lib](https://github.com/adafruit/Adafruit_MPR121/tree/3160fc4df501912bcf34bfae00e65c6f18c0820a/examples/MPR121test).

**Comment by max2play** [comment]
Thanks for your answer! I tried the touch example and this is working perfectly - recognizing all inputs. When not using touch it is also working with your sketchbook. And the connection error does not happen immediatly, but after around 5-10 seconds. I am using a Raspberry Pi connected via USB to the arduino and also tried a lower baud rate, but this did not fix the problem... do you have any other idea what it might be?

**After some debugging (print out read_char and read_short in arduino.py) I saw the following:**
...
('D',)
(0,)
(328,)
(334,)
(451,)
(460,)
(460,)
(462,)
(464,)
(465,)
(455,)
(440,)
(430,)
(422,)
('D',)
(0,)
(328,)
(49921,)
(52225,)
(52225,)
(52737,)
(53249,)
(53505,)
(50945,)
(47105,)
(44545,)
(42497,)
(17409,)
ValueError: Expected one command of ['B', 'D'], got 

The first lines are correct and right before the connection drops the values are longer than they should be (but the longer values are quite consistant the same - so it does not seem like a bad connection problem)... 

**When using just one touch button in the configuration it works (click events get noticed):**
('H',)
('\x02',)
('S',)
Arbalet hardware initialization successful
('D',)
(0,)
(327,)
('D',)
(0,)
(328,)
('D',)
(0,)
(328,)
...

**Comment by ymollard** [comment]
What's your Arduino board model?

Looks like a 1-Byte offset appearing after the filtered data of the first key. Try to reduce the [refresh rate](https://github.com/arbalet-project/arbasdk/blob/master/arbalet/config/config150touch.json#L8) to 20Hz. It might be too much data at once at 50Hz. I never tried to overload the serial bus or overflow the serial cache, so some Bytes could been dropped there.

**Comment by max2play** [comment]
I have an Arduino Leonardo. Yes, there is an offset - like 1 Byte coming in too much - I can take care of this to skip the wrong values and replace them by the values that are expected if no touchevent happened, but I'd really like to know why this happens. I also reduced the refresh rate and it does not change anything.

**Comment by ymollard** [comment]
According to my experience Leonardo is the best board for this project :P
Have you tried other numbers of touch keys, between 1 and 12?
Also try to `write_short(0)` [here](https://github.com/arbalet-project/arbasdk/blob/master/hardware/arduino/Arbalet/examples/Arbalink_WS2812B/Arbalink_WS2812B.ino#L135), it could be an overflow of some `uint16_t` there.

**Comment by max2play** [comment]
Thanks for your help! I added write_short(0) and the error is gone... I think it might be the crappy touch-sensor that I have (not the original from Adafruit, but also a mpr121), that is causing the error. Anyway I added some error handling in case the values do not match the expected ones and it is working for me now.

**Comment by ymollard** [comment]
I wouldn't blame the sensor so quickly, especially because you said it was working well alone. Would you mind trying the 2 tests below:

- keep `write_short(0)` but also run `touch->filteredData(key);` in a next line
- write 65535 instead of 0, which is the maximum uint16 value, without any access to the filtered data

That would allow to see if accessing the filtered data has a side effect or if there is a bug in the protocol.

**Comment by max2play** [comment]
Ok - the transfer of the data is working fine. With 65535 or 0 it works (all values get transfered correctly), but as soon as I start calling "touch->filteredData(key);" even without "write_short" (as you asked me to) the errors start. 
Not really sure how to debug this... As you are just using the library from Adafruit, maybe it is now time to blame my sensor :) ?

**Comment by ymollard** [comment]
Removing `write_short` causes the Arduino not to respect the communication protocol so communication will fail _de facto_. Thus, never add or remove any `write_x` or `read_x`. 

Maybe also make sure that key does not goes beyond [0, 11] by copying `key` to a short and returning it instead of the filtered data. You can also print `touch_type` the same way, that should be always `12`.

I'm very prudent blaming 3rd party code or hardware, at low level a software bug may have consequences in a totally different section, especially on microcontrollers.

I'm curious: what power supply are you using to power both the LEDs and the RasPi ? Its amperage? [Users reported 5A is theoretically a bit low](https://github.com/arbalet-project/arbadoc/issues/5) (albeit sufficient in practice) but it's even worse with a RasPi on it.

**Comment by max2play** [comment]
Thanks for your explanation.

I just changed `write_short(touch->filteredData(key);)` to `write_short(0);touch->filteredData(key);` and thought that this should work - but it did not. I did not remove or add a write / read and kept the protocol working. The function `filteredData` should not be sending Data by its own, but if it is executed the error occurs. As your code (and Adafruit library) is working for everyone else, it is not very likely that there is an error in the library.

The variables `touch_type` and the key within the loop are fine. When I switch the config to `calibrated=false` and just use the `touch->touched()` to get the button events and remove the call of the filteredData function in the sketchbook, I get no errors and I can use touch. But I cannot set custom sensitivity in this mode.

This might be interesting: When I run `touch->baselineData` instead of `touch->filteredData` I get no errors. I think it can be narrowed down to the `uint16_t Adafruit_MPR121::readRegister16(uint8_t reg)` function that is used for filteredData.

My powersupply has 10A and should deliver enough power for RPi, Arduino and LED stripes.

You can close this issue if you like, as my workaround to catch wrong values is working.

Cheers,
Stefan
